# Custom Language File for Launcher Customizer

[ejs.app]
title = "Northium Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/northiumnetwork/NorthiumLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/TSXZJpccmz"

[ejs.settings]
sourceGithubLink = "https://github.com/northiumnetwork/NorthiumLauncher"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "#"
welcomeDescription = "#"
welcomeDescCTA = "#"
